Update android.yml

diff --git a/.github/workflows/android.yml b/.github/workflows/android.yml
--- a/.github/workflows/android.yml
+++ b/.github/workflows/android.yml
@@ -39,18 +39,12 @@ jobs:
           path: app/build/outputs/apk/debug/
 
       - name: Set build status
-        uses: actions/github-script@v7.0.1
-        with:
-          script: |
-            const conclusion = context.job.status === 'success' ? 'success' : 'failure';
-            github.rest.repos.createCommitStatus({
-              owner: context.repo.owner,
-              repo: context.repo.repo,
-              sha: context.sha,
-              state: conclusion,
-              context: 'GitHub Actions',
-              description: 'Build and Test',
-            });
+        run: |
+          if [[ $? = 0 ]]; then  # Check if the previous steps succeeded
+            echo "::set-output name=status::success"
+          else
+            echo "::set-output name=status::failure"
+          fi
 
   notify:
     runs-on: ubuntu-latest
